print("\nWelcome to the Band Name Generator: ")
print("=====================================\n")
city_name = input("What's the name of the city you grew up in? ")
pet_name = input("What's your pet's name? ")
print("\nYour band name could be " + city_name + " " + pet_name)
